# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@2
  inputs:
    versionSpec: '16.x'
    addToPath: true

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Azure Subscription>'
    appName: '<App Name>'
    package: '$(Build.ArtifactStagingDirectory)/drop/*.zip'
